trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Publish
    steps:
      - script: |
          set -e
          npm ci
          npm run generate
          npx gh-pages --repo https://$(GITHUB_TOKEN)@github.com/stencila/status.git -d dist
        env:
          GIT_AUTHOR_NAME: Stencila CI Bot
          GIT_AUTHOR_EMAIL: ci@stenci.la
          GIT_COMMITTER_NAME: Stencila CI Bot
          GIT_COMMITTER_EMAIL: ci@stenci.la
        displayName: 'Generate and deploy'
